name: thelettersryewrote
favicon: null
layout_spectrum: 0.09246937581337988
typography_spectrum: 0.7177927945740521
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffe9e8'
    - '#e47297'
    - '#000000'
    - '#aa0114'
    - '#606060'
  brandStrength: 0.17862499435432255
  lightness: 0.1121530937962234
  saturation: 0.4051349435467273
  rhythmicContrast: 0.8045628902036697
purpose: []
